### ISSUE TITLE
First-Website review

### ISSUE THREAD

**Issue by Rumbie-Mudzie7** [ThamiMk/First-Website#1]
Great work and project concept, 👏👏however, the project could be improved by implementing the following concepts:

- [x] Placing all images in one folder.
- [x] Including sectional elements like section and/or article for semantic markup.
- [x] You can improve the README.MD file by including screenshots and live demo links.
Refer to the following links for more insight on writing a good readme.MD file.
[https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project](URL)
[https://www.youtube.com/watch?v=RZ5vduluea4](URL)
[https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/](url)

**Comment by ThamiMk** [comment]
Improvements implemented
